### PR TITLE
Add basic sharing functionality

### PR DESCRIPTION
**Pull request by drobinson**
Awesome tool - I saw your post on Reddit and found that everyone was sharing the teams they built with texts lists.  I thought it would be cool if they could share them with a link to easily view strengths/weaknesses, so I implemented this via url-hash updates.

The initial load isn't showing strengths/weaknesses for some reason, and I don't have time right at this moment to test that out (though, originally it was a CORS problem) and fix this.  Regardless I figured you could use the PR as a starting point or idea for some more verbose functionality.  Also, I apologize if any of my JS offends you...I'm not a JS first dev :)

Again, thanks for the tool!

### CODE REVIEW

**Review by richi3f-zz — APPROVED** [review]
Hey, thanks for adding this feature! I have tested in a local setting and it works neatly. The team type analysis is not working right now because weaknesses, immunites and resistances are added programmatically. It's a matter of moving some lines. :)

**Comment by drobinson** [comment]
That's the weird part - I added pkmn to the team at the end of onload (after the type info is added) using the same function used for onclick, which includes the call to updateTeamTypeAnalysis().

**Review by richi3f-zz — APPROVED** [review]

**Comment by richi3f-zz** [comment]
Putting those lines at the end of the xml parsing bits (instead of at the end of onload) worked for me

**Comment by drobinson** [comment]
Ah I was about to fix this, but I see you also fixed it!  Excited to start sharing teams with everyone.

**Pull request closed without merging**
